name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:
      - name: DumpApiKey
        run: echo ${{ secrets.NUGETAPIKEY }}

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build and test solution
        run: dotnet test

      - name: Pack solution
        run: dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push out\*.nupkg --skip-duplicate --no-symbols true --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }}
        